/openapi.json:
  get:
    summary: OpenAPI JSON
    description: OpenAPI JSON file for the API
    operationId: openapi-json
    tags:
      - endpoint
    responses:
      '200':
        description: OK
        content:
          application/json:
            schema:
              type: string
              format: binary
/openapi.yaml:
  get:
    summary: OpenAPI YAML
    description: OpenAPI YAML file for the API
    operationId: openapi-yaml
    tags:
      - endpoint
    responses:
      '200':
        description: OK
        content:
          application/x-yaml:
            schema:
              type: string
              format: binary
