version: '3'
services:
  database:
    image: postgres:15-alpine
    container_name: canister-db
    ports:
      - 5432:5432
    networks:
      - canister
    environment:
      POSTGRES_PASSWORD: pg
      POSTGRES_USER: cnstr
    volumes:
      - db:/var/lib/postgresql/data
  search:
    image: typesense/typesense:0.25.0.rc25
    container_name: canister-search
    ports:
      - 8108:8108
    networks:
      - canister
    environment:
      TYPESENSE_API_KEY: typesense
      TYPESENSE_DATA_DIR: /data
      TYPESENSE_ENABLE_CORS: "true"
    volumes:
      - typesense:/data
  pipeline:
    image: timberio/vector:0.29.X-distroless-libc
    container_name: canister-pipeline
    ports:
      - 8687:8687
    volumes:
      - ./vector.toml:/etc/vector/vector.toml:ro
    networks:
      - canister
    depends_on:
      - sink
  sink:
    image: clickhouse/clickhouse-server:latest
    container_name: canister-sink
    ports:
      - 8123:8123
      - 9000:9000
    volumes:
      - sink:/var/lib/clickhouse
      - logs:/var/log/clickhouse-server
      - ./clickhouse.sh:/docker-entrypoint-initdb.d/clickhouse.sh:ro
    networks:
      - canister
    environment:
      CLICKHOUSE_DB: canister
      CLICKHOUSE_USER: canister
      CLICKHOUSE_PASSWORD: canister
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: '1'
  grafana:
    image: grafana/grafana:latest
    container_name: canister-grafana
    ports:
      - 4000:3000
    volumes:
      - dashboard:/var/lib/grafana
    networks:
      - canister
    depends_on:
      - pipeline
      - sink
      - database
volumes:
  sink:
  logs:
  dashboard:
  db:
  typesense:
networks:
  canister:
    driver: bridge
