version: '3'
services:
  database:
    image: postgres:14-alpine
    container_name: canister-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pg
      POSTGRES_USER: cnstr
    volumes:
      - db:/var/lib/postgresql/data

  search:
    image: typesense/typesense:0.23.0
    container_name: canister-search
    ports:
      - 8108:8108
    environment:
      TYPESENSE_API_KEY: typesense
      TYPESENSE_DATA_DIR: /data
      TYPESENSE_ENABLE_CORS: "true"
    volumes:
      - typesense:/data

volumes:
  db:
  search:
  typesense:
