ARG CANISTER_META_NAME
ARG CANISTER_META_DESC
ARG CANISTER_META_EMAIL
ARG CANISTER_META_COPYRIGHT
ARG CANISTER_API_ENDPOINT
ARG CANISTER_OPENAPI_ID
ARG CANISTER_OPENAPI_TOKEN

FROM rust:1.79 AS builder
WORKDIR /app

ADD . .
RUN CANISTER_META_NAME=${CANISTER_META_NAME} \
	CANISTER_META_DESC=${CANISTER_META_DESC} \
	CANISTER_META_EMAIL=${CANISTER_META_EMAIL} \
	CANISTER_META_COPYRIGHT=${CANISTER_META_COPYRIGHT} \
	CANISTER_API_ENDPOINT=${CANISTER_API_ENDPOINT} \
	CANISTER_UPLOAD_OPENAPI=true \
	CANISTER_OPENAPI_ID=${CANISTER_OPENAPI_ID} \
	CANISTER_OPENAPI_TOKEN=${CANISTER_OPENAPI_TOKEN} \
	cargo build --release -p api

FROM gcr.io/distroless/cc-debian12
COPY --from=builder /app/target/release/api /
CMD ["./api"]

EXPOSE 3000
