ARG CANISTER_META_NAME
ARG CANISTER_META_DESC
ARG CANISTER_META_EMAIL
ARG CANISTER_META_COPYRIGHT
ARG CANISTER_API_ENDPOINT
ARG CANISTER_OPENAPI_ID
ARG CANISTER_OPENAPI_TOKEN

FROM rust:1.79 as builder
ENV UPLOAD_OPENAPI=true
WORKDIR /app

ADD . .
RUN cargo build --release -p api

FROM gcr.io/distroless/cc-debian12
COPY --from=builder /app/target/release/api /
CMD ["./api"]

EXPOSE 3000
