version: '3'

tasks:
  dev:
    desc: 'Run the project locally using Docker Compose'
    cmds:
      - cmd: docker compose -p canister up -d
      - defer: docker compose -p canister down
      - cmd: cargo watch -- cargo run --bin api
        ignore_error: true
  deploy:
    desc: 'Deploys the latest build via Github Actions'
    cmds:
      - cmd: 'if [ -z "{{.CLI_ARGS}}" ]; then echo "Usage: task deploy -- <major|minor|patch|release|rc|beta|alpha>"; exit 1; fi'
        silent: true
      - cmd: echo "major minor patch release rc beta alpha" | grep -w -q "{{.CLI_ARGS}}" || exit 1
        silent: true
      - cmd: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer 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"\
            -H "X-GitHub-Api-Version: 2022-11-28" \
            'https://api.github.com/repos/cnstr/ci/actions/workflows/api.yaml/dispatches' \
            -d '{"ref":"main","inputs":{"bump_type":"{{.CLI_ARGS}}"}}'
