version: '3'

tasks:
  dev:
    desc: 'Run the project locally using Docker Compose'
    cmds:
      - cmd: docker compose -p canister up -d
      - defer: docker compose -p canister down
      - cmd: cargo watch -- cargo run --bin api
        ignore_error: true
  build:
    desc: 'Builds the production container'
    cmds:
      - cmd: cargo release -p api -p deploy --no-publish --sign-commit --sign-tag --tag-prefix '' --push-remote origin {{.CLI_ARGS}}
        silent: true
      - cmd: cargo release -p api -p deploy --no-publish --sign-commit --sign-tag --tag-prefix '' --push-remote origin -x {{.CLI_ARGS}}
        silent: true
  deploy:
    desc: 'Deploys the latest production build to Kubernetes'
    cmds:
      - cmd: cargo run --bin deploy
        silent: true
      - cmd: git add kubernetes/api.yaml
        silent: true
      - cmd: 'git commit -m "chore: update k8s deployment to $(git tag --sort=-v:refname | cut -c 2- | head -n 1)"'
        silent: true
      - cmd: git push
        silent: true
      - cmd: kubectl apply -f kubernetes/api.yaml
        silent: true
