version: '3'

tasks:
  dev:
    desc: 'Run the project locally using Docker Compose'
    cmds:
      - cmd: docker compose -p canister up -d
      - defer: docker compose -p canister down
      - cmd: cargo watch -- cargo run --bin api
        ignore_error: true
  build:
    desc: 'Build the project'
    env:
      CANISTER_META_NAME: 'Canister'
      CANISTER_META_DESC: 'A high-speed search engine for APT software packages.'
      CANISTER_META_EMAIL: 'support@canister.me'
      CANISTER_META_COPYRIGHT: 'Aarnav Tale (c) {year}'
      CANISTER_API_ENDPOINT: 'https://api.canister.me/v2'
    cmds:
      - cmd: cargo build {{.cli_args}}
