[sources.http_ingest]
type = "http_server"
address = "0.0.0.0:8687"
encoding = "json"

[sinks.console]
type = "console"
inputs = ["http_ingest"]
target = "stdout"
encoding.codec = "json"

[sinks.clickhouse]
type = "clickhouse"
inputs = ["http_ingest"]
endpoint = "http://sink:8123"
auth.strategy = "basic"
auth.user = "canister"
auth.password = "canister"
database = "canister"
table = "download_events"
skip_unknown_fields = true
