version: '3'
services:
  api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    container_name: canister-api
    ports:
      - 8080:3000
      - 9229:9229
    environment:
      NODE_ENV: development
    volumes:
      - ../src:/app/src
    depends_on:
      - database
      - search

  database:
    image: postgres:14-alpine
    container_name: canister-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: pg
      POSTGRES_USER: cnstr
    volumes:
      - db:/var/lib/postgresql/data

  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    container_name: canister-search
    ports:
      - 9300:9300
      - 9200:9200
    environment:
      bootstrap.memory_lock: "true"
      discovery.type: single-node
      xpack.security.enabled: "false"
      xpack.security.http.ssl.enabled: "false"
    volumes:
      - search:/usr/share/elasticsearch/data

volumes:
  db:
  search:
