apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: canister
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: api
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: canister
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      restartPolicy: Always
      imagePullSecrets:
      - name: google-cloud
      containers:
      - name: api
        image: us-east4-docker.pkg.dev/aarnavtale/canister/api:2.4.20
        ports:
        - name: api
          containerPort: 3000
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
