apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: canister
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: api
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: canister
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      restartPolicy: Always
      imagePullSecrets:
        - name: aerum-registry
      containers:
        - name: api
          image: aerum.co/canister/api:2.1.5
          ports:
            - name: api
              containerPort: 3000
