apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: canister
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      restartPolicy: Always
      imagePullSecrets:
        - name: aerum-registry
      containers:
        - name: api
          image: aerum.co/canister/api:2.0.4
          ports:
            - name: api
              containerPort: 3000
