apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
  namespace: canister
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-production"

spec:
  rules:
  - host: api.canister.me
    http:
      paths:
      - pathType: Prefix
        path: /v2/
        backend:
          service:
            name: api
            port:
              number: 3000
  tls:
  - hosts:
    - 'api.canister.me'
    secretName: api-tls
