apiVersion: v1
kind: ConfigMap
metadata:
  name: vector
  namespace: canister
data:
  vector.toml: |
    [sources.http_ingest]
    type = "http_server"
    address = "0.0.0.0:8687"
    encoding = "json"
    
    [sinks.clickhouse]
    type = "clickhouse"
    inputs = ["http_ingest"]
    endpoint = "http://clickhouse:8123"
    auth.strategy = "basic"
    auth.user = "canister"
    auth.password = "XyNAg9tQ5Edk0ewmwkTX"
    database = "canister"
    table = "download_events"
    skip_unknown_fields = true
---
apiVersion: v1
kind: Service
metadata:
  name: vector
  namespace: canister
spec:
  ports:
    - port: 8687
      targetPort: 8687
  selector:
    app: com.tale.canister.vector
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vector
  namespace: canister
spec:
  replicas: 1
  selector:
    matchLabels:
      app: com.tale.canister.vector
  template:
    metadata:
      labels:
        app: com.tale.canister.vector
    spec:
      restartPolicy: Always
      containers:
      - name: vector
        image: timberio/vector:0.29.X-distroless-libc
        ports:
        - name: vector
          containerPort: 8687
        volumeMounts:
        - name: vector
          mountPath: /etc/vector
      volumes:
      - name: vector
        configMap:
          name: vector
          items:
          - key: vector.toml
            path: vector.toml
