name: API Deploy

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Login to tale.me
        uses: docker/login-action@v2.1.0
        with:
          registry: tale.me
          username: bot-github
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: Build container image
        run: docker build -t tale.me/canister/api:$(echo "$GITHUB_REF_NAME" | cut -c 2-) --build-arg BUILD_DATE=$(date --rfc-3339=date) --build-arg VERSION=$(echo "$GITHUB_REF_NAME" | cut -c 2-) --build-arg GIT_STATE=$GITHUB_SHA .
      - name: Push container image to tale.me
        run: docker push tale.me/canister/api:$GITHUB_REF_NAME
