name: Deploy API
on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Load configuration manifest
        run: echo "$MANIFEST_BASE64" | base64 -d > manifest.yaml
        env:
          MANIFEST_BASE64: ${{ secrets.API_MANIFEST }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/arm64
          cache-to: type=registry,ref=ghcr.io/cnstr/api-cache,compression=zstd
          cache-from: type=registry,ref=ghcr.io/cnstr/api-cache

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Configure Kubernetes
        uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.OKE_CONFIG }}
          kubectl-version: ${{ vars.OKE_VERSION }}

      - name: Rollout new container build
        run: kubectl rollout restart -n canister deploy/api
