name: Deploy API
on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build
    runs-on: self-hosted
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Import secrets
        id: secrets
        uses: hashicorp/vault-action@v2
        with:
          method: 'jwt'
          url: ${{ vars.HASHICORP_VAULT_URL }}
          role: ${{ vars.HASHICORP_VAULT_ROLE }}
          jwtGithubAudience: ${{ vars.HASHICORP_VAULT_AUD }}
          secrets: |
            kv/data/canister/api *

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Load configuration manifest
        run: echo "$MANIFEST_BASE64" | base64 -d > manifest.yaml
        env:
          MANIFEST_BASE64: ${{ secrets.API_MANIFEST }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/arm64
          cache-to: type=registry,ref=ghcr.io/cnstr/api-cache,compression=zstd
          cache-from: type=registry,ref=ghcr.io/cnstr/api-cache
          build-args: |
            CANISTER_META_NAME=${{ steps.secrets.outputs.CANISTER_META_NAME }}
            CANISTER_META_DESC=${{ steps.secrets.outputs.CANISTER_META_DESC }}
            CANISTER_META_EMAIL=${{ steps.secrets.outputs.CANISTER_META_EMAIL }}
            CANISTER_META_COPYRIGHT=${{ steps.secrets.outputs.CANISTER_META_COPYRIGHT }}
            CANISTER_API_ENDPOINT=${{ steps.secrets.outputs.CANISTER_API_ENDPOINT }}
            CANISTER_OPENAPI_ID=${{ steps.secrets.outputs.CANISTER_OPENAPI_ID }}
            CANISTER_OPENAPI_TOKEN=${{ steps.secrets.outputs.CANISTER_OPENAPI_TOKEN }}
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Configure Kubernetes
        uses: tale/kubectl-action@v1
        with:
          base64-kube-config: ${{ secrets.OKE_CONFIG }}
          kubectl-version: ${{ vars.OKE_VERSION }}

      - name: Rollout new container build
        run: kubectl rollout restart -n canister deploy/api
